version: '3.9'

services:
  uptime-kuma:
    build: .
    container_name: uptime_kuma
    ports:
      - "4000:4000"
    env_file:
      - ../config/config.env
    volumes:
      - ./database.sqlite:/app/database.sqlite
    restart: unless-stopped
